import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { spawnSync } from "node:child_process";

const moduleRoot = path.resolve(import.meta.dirname, "..");
const projectRoot = path.resolve(moduleRoot, "..");
const temp = fs.mkdtempSync(path.join(os.tmpdir(), "pulsede-generator-test-"));
const fixture = path.join(temp, "fixture");
fs.mkdirSync(fixture);
for (const extension of ["mp3", "jpg", "txt"]) fs.copyFileSync(path.join(projectRoot, `12_Das WIR gewinnt.${extension}`), path.join(fixture, `fixture.${extension}`));
const out = path.join(temp, "run");
const reservations = path.join(temp, "reservations.json");
fs.writeFileSync(reservations, JSON.stringify({ version:1, reservations:[] }), "utf8");
const generator = path.join(moduleRoot, "tools", "song-upgrade.mjs");
const common = ["--root", projectRoot, "--reservation-file", reservations];
const baselineRun = spawnSync(process.execPath, [generator, ...common, "--inspect"], { encoding:"utf8" });
assert.equal(baselineRun.status, 0, baselineRun.stderr);
const baseline = JSON.parse(baselineRun.stdout);
const expectedNumber = baseline.nextNumber;
const prefix = `${String(expectedNumber).padStart(2,"0")}_Generator Testlauf`;
const expectedId = `song-${String(baseline.nextIndex + 1).padStart(2,"0")}`;
const usedAfterReservation = new Set([...baseline.usedNumbers, expectedNumber]);
let expectedAfterReservation = 1; while (usedAfterReservation.has(expectedAfterReservation)) expectedAfterReservation += 1;
const run = spawnSync(process.execPath, [generator, ...common, "--input", fixture, "--title", "Generator Testlauf", "--hm", "01,03", "--featured", "ja", "--out", out], { encoding: "utf8" });
assert.equal(run.status, 0, run.stderr);
const report = JSON.parse(fs.readFileSync(path.join(out, "integrationsbericht.json"), "utf8"));
assert.equal(report.baseline.songs, baseline.songs);
assert.equal(report.song.number, expectedNumber);
assert.equal(report.song.index, baseline.nextIndex);
assert.deepEqual(report.song.hms, ["01", "03"]);
assert.equal(report.safety.productionChanged, false);
assert.ok(fs.existsSync(path.join(out, "testkopie", "START_LOKALTEST.cmd")));
assert.ok(fs.existsSync(path.join(out, "github-paket", "v1b", "data", "catalog.json")));
assert.ok(fs.existsSync(path.join(out, "lokales-upload-paket", `${prefix}.mp3`)));
const catalog = JSON.parse(fs.readFileSync(path.join(out, "testkopie", "v1b", "data", "catalog.json"), "utf8"));
assert.equal(catalog.songs.length, baseline.songs + 1);
assert.ok(catalog.categories.find(x => x.number === "01").songIds.includes(expectedId));
assert.ok(!catalog.categories.find(x => x.number === "02").songIds.includes(expectedId));
const testHome = fs.readFileSync(path.join(out, "testkopie", "PulseDE_Home_A1_TESTRAHMEN_V4.html"), "utf8");
assert.match(testHome, /src="PulseDE_HM_PLAYER_LINKS_A1_V4\.html"/);
assert.match(testHome, /src="PulseDE_HM_SONGTEXT_RECHTS_A1_V4\.html"/);
assert.match(testHome, /src="PulseDE_HM_EXPLORER_TEST_V1\.html"/);
assert.doesNotMatch(testHome, /pulsede2026-hb\.github\.io/);
const testPlayer = fs.readFileSync(path.join(out, "testkopie", "PulseDE_HM_PLAYER_LINKS_A1_V4.html"), "utf8");
const testExplorer = fs.readFileSync(path.join(out, "testkopie", "PulseDE_HM_EXPLORER_TEST_V1.html"), "utf8");
assert.ok(testPlayer.includes(`${prefix}.mp3`));
assert.ok(testPlayer.includes(`${prefix}.jpg`));
assert.doesNotMatch(testPlayer, /,,/);
const playlistBody = testPlayer.match(/const\s+playlist\s*=\s*\[([\s\S]*?)\n\s*\];/)[1];
const playlistEntries = [...playlistBody.matchAll(/"([^"]+\.mp3)"/g)].map(match => match[1]);
assert.equal(playlistEntries.length, baseline.songs + 1);
assert.equal(playlistEntries[baseline.nextIndex].endsWith(`${prefix}.mp3`), true);
assert.ok(testExplorer.includes(`> ${String(expectedNumber).padStart(2,"0")} Generator Testlauf`));
const reserve = spawnSync(process.execPath, [generator, ...common, "--reserve-run", out], { encoding:"utf8" });
assert.equal(reserve.status, 0, reserve.stderr);
const reservationResult = JSON.parse(reserve.stdout);
assert.equal(reservationResult.reservation.number, expectedNumber);
assert.equal(reservationResult.nextNumber, expectedAfterReservation);
const inspectReserved = spawnSync(process.execPath, [generator, ...common, "--inspect"], { encoding:"utf8" });
assert.equal(JSON.parse(inspectReserved.stdout).nextNumber, expectedAfterReservation);
const duplicate = spawnSync(process.execPath, [generator, ...common, "--input", fixture, "--title", "Bleib bei mir", "--hm", "01", "--featured", "nein", "--out", path.join(temp, "duplicate")], { encoding: "utf8" });
assert.notEqual(duplicate.status, 0);
assert.match(duplicate.stderr, /Kollisionen/);
const wrongNumber = spawnSync(process.execPath, [generator, ...common, "--input", fixture, "--title", "Falsche Nummer", "--hm", "01", "--featured", "nein", "--number", "60", "--out", path.join(temp, "wrong-number")], { encoding: "utf8" });
assert.notEqual(wrongNumber.status, 0);
assert.match(wrongNumber.stderr, new RegExp(`ausschließlich Nummer ${expectedAfterReservation}`));
console.log("Generator: 29 Prüfungen erfolgreich.");
